# Generated by Django 6.0.3 on 2026-04-02 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': [['cart', 'product']]},
        ),
    ]
