# Generated by Django 6.0.3 on 2026-04-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_cartitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['cart', 'product']},
        ),
    ]
