# Generated by Django 6.0.3 on 2026-04-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_categorybanner_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorybanner',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
