# Generated by Django 6.0.3 on 2026-04-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_image_categorybanner_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybanner',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='categories/banners/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='products/images'),
        ),
    ]
